### ISSUE TITLE
How cleaning steps for creating the reviews.csv file

### ISSUE THREAD

**Issue by andysingal** [sinanuozdemir/oreilly-hands-on-gpt-llm#3]
Hi Sinan,
      I was working on the Multi Task notebook and wanted to check what cleaning steps did you do to create reviews.csv.
Thanks,
Andy

**Comment by sinanuozdemir** [comment]
Happy to help here! It's actually raw data from here: https://www.kaggle.com/datasets/snap/amazon-fine-food-reviews
